<?php

namespace AppBundle\Repository;

/**
 * FundTransferTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FundTransferTransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
